
SET TERM ^ ;

CREATE OR ALTER PROCEDURE MANUTENCAOPRODSEMIMPOSTO (
    IDPERFILFISCAL INTEGER,
    IDPRODUTO INTEGER)
RETURNS (
    IDPERFILFISCALGERADO INTEGER)
AS
DECLARE VARIABLE FID INTEGER;
DECLARE VARIABLE PID INTEGER;
DECLARE VARIABLE FE21IBTAXFALIQMUN NUMERIC(15,2);
DECLARE VARIABLE FE22IBTAXFALIEST NUMERIC(15,2);
DECLARE VARIABLE FE23IBTAXFALIQFED NUMERIC(15,2);
DECLARE VARIABLE FE24IBTAXFALIIMP NUMERIC(15,2);
DECLARE VARIABLE FE40ICMSFPREDBC NUMERIC(15,2);
DECLARE VARIABLE FE107ACIONAFCPB INTEGER;
DECLARE VARIABLE FE108OUTFALIQICMS NUMERIC(15,2);
DECLARE VARIABLE FE109OUTFCFOPIN VARCHAR(5);
DECLARE VARIABLE FE109OUTFCFOPOUT VARCHAR(5);
DECLARE VARIABLE FE109OUTFCSTCSOSN VARCHAR(5);
DECLARE VARIABLE FE110OUTFPISCST VARCHAR(5);
DECLARE VARIABLE FE111OUTFPISALIQ NUMERIC(15,2);
DECLARE VARIABLE FE112OUTFCOFINSCST VARCHAR(5);
DECLARE VARIABLE FE113FOUTCOFINSALIQ NUMERIC(15,2);
DECLARE VARIABLE FE114OUTFPMVAST NUMERIC(15,2);
DECLARE VARIABLE FE115OUTFPICMSST NUMERIC(15,2);
DECLARE VARIABLE FE116OUTFPREDBCST NUMERIC(15,2);
DECLARE VARIABLE FE117OUTFMODBCICMS INTEGER;
DECLARE VARIABLE FE118OUTFMODBCICMSST INTEGER;
DECLARE VARIABLE FE11FISCALFCEST VARCHAR(12);
DECLARE VARIABLE FE10FISCALFNCM VARCHAR(12);
BEGIN
 SELECT F.ID,
        F.E107ACIONAFCPB,
        F.E108OUT_ALIQICMS,
        F.E109OUT_CFOPIN,
        F.E109OUT_CFOPOUT,
        F.E109OUT_CSTCSOSN,
        F.E110OUT_PISCST,
        F.E111OUT_PISALIQ,
        F.E112OUT_COFINSCST,
        F.E113_OUTCOFINSALIQ,
        F.E114OUT_PMVAST,
        F.E115OUT_PICMSST,
        F.E116OUT_PREDBCST,
        F.E117OUT_MODBCICMS,
        F.E118OUT_MODBCICMSST,
        F.E10FISCAL_NCM,
        F.E11FISCAL_CEST,
        F.E21IBTAX_ALIQMUN,
        F.E22IBTAX_ALIEST,
        F.E23IBTAX_ALIQFED,
        F.E24IBTAX_ALIIMP,
        F.E40ICMS_PREDBC FROM PERFIS_IN F
        WHERE F.ID = :IDPERFILFISCAL
   INTO
        :FID,
        :FE107ACIONAFCPB,
        :FE108OUTFALIQICMS,
        :FE109OUTFCFOPIN,
        :FE109OUTFCFOPOUT,
        :FE109OUTFCSTCSOSN,
        :FE110OUTFPISCST,
        :FE111OUTFPISALIQ,
        :FE112OUTFCOFINSCST,
        :FE113FOUTCOFINSALIQ,
        :FE114OUTFPMVAST,
        :FE115OUTFPICMSST,
        :FE116OUTFPREDBCST,
        :FE117OUTFMODBCICMS,
        :FE118OUTFMODBCICMSST,
        :FE10FISCALFNCM,
        :FE11FISCALFCEST,
        :FE21IBTAXFALIQMUN,
        :FE22IBTAXFALIEST,
        :FE23IBTAXFALIQFED,
        :FE24IBTAXFALIIMP,
        :FE40ICMSFPREDBC;




   INSERT INTO CADPROD_PERFILSAIDA (
    F01IDPERFIL,
    F02E107ACIONAFCPB,
    F03E108OUT_ALIQICMS,
    F04E109OUT_CFOPIN,
    F05E109OUT_CFOPOUT,
    F06E109OUT_CSTCSOSN,
    F07E110OUT_PISCST,
    F08E111OUT_PISALIQ,
    F09E112OUT_COFINSCST,
    F10E113_OUTCOFINSALIQ,
    F11E114OUT_PMVAST,
    F12E115OUT_PICMSST,
    F13E116OUT_PREDBCST,
    F14E117OUT_MODBCICMS,
    F15E118OUT_MODBCICMSST,
    F16E10FISCAL_NCM,
    F17E11FISCAL_CEST,
    F18E21IBTAX_ALIQMUN,
    F19E22IBTAX_ALIEST,
    F20E23IBTAX_ALIQFED,
    F21E24IBTAX_ALIIMP,
    F22E40ICMS_PREDBC)

  VALUES (
    :FID,
    :FE107ACIONAFCPB,
    :FE108OUTFALIQICMS,
    :FE109OUTFCFOPIN,
    :FE109OUTFCFOPOUT,
    :FE109OUTFCSTCSOSN,
    :FE110OUTFPISCST,
    :FE111OUTFPISALIQ,
    :FE112OUTFCOFINSCST,
    :FE113FOUTCOFINSALIQ,
    :FE114OUTFPMVAST,
    :FE115OUTFPICMSST,
    :FE116OUTFPREDBCST,
    :FE117OUTFMODBCICMS,
    :FE118OUTFMODBCICMSST,
    :FE10FISCALFNCM,
    :FE11FISCALFCEST,
    :FE21IBTAXFALIQMUN,
    :FE23IBTAXFALIQFED,
    :FE23IBTAXFALIQFED,
    :FE24IBTAXFALIIMP,
    :FE40ICMSFPREDBC)
   RETURNING ID
   INTO :PID;

  EXECUTE STATEMENT 'ALTER TRIGGER ATUALIZA_CARGA INACTIVE';
   UPDATE CADPRODUTOS X SET X.C163IDPERFILFISCAL = :PID  WHERE X.ID = :IDPRODUTO;
  EXECUTE STATEMENT 'ALTER TRIGGER ATUALIZA_CARGA ACTIVE';

  /* PROCEDURE TEXT */
  SUSPEND;
  IDPERFILFISCALGERADO = :PID;
END^

SET TERM ; ^

COMMENT ON PARAMETER MANUTENCAOPRODSEMIMPOSTO.IDPERFILFISCAL IS
'PERFIS FISCAIS DA TAELA PERFIS_IN';

/* FOLLOWING GRANT STATETEMENTS ARE GENERATED AUTOMATICALLY */

GRANT SELECT ON PERFIS_IN TO PROCEDURE MANUTENCAOPRODSEMIMPOSTO;
GRANT INSERT ON CADPROD_PERFILSAIDA TO PROCEDURE MANUTENCAOPRODSEMIMPOSTO;
GRANT SELECT,UPDATE ON CADPRODUTOS TO PROCEDURE MANUTENCAOPRODSEMIMPOSTO;

/* EXISTING PRIVILEGES ON THIS PROCEDURE */

GRANT EXECUTE ON PROCEDURE MANUTENCAOPRODSEMIMPOSTO TO SYSDBA;
